### ISSUE TITLE
MeepMeep.wav versus MeepMeep.ogg?

### ISSUE THREAD

**Issue by Sslaxx** [coderman64/flow-engine#2]
In the `audio` folder are the files `MeepMeep.wav` and `MeepMeep.ogg`. The wave file is 42MB, the OGG 3.2MB. The project appears to be using the .wav file, when the .ogg file appears to be functionally identical.

**Comment by coderman64** [comment]
I think when I created this project, I didn't know how to loop .ogg files. Now that I do, this would make a lot of sense.
